version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    container_name: refresh_token_demo_app
    restart: always
    command: sleep infinity
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh:cached
      - ~/.gitconfig:/home/vscode/.gitconfig:cached
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql:8.0.34
    container_name: refresh_token_demo_database
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: refresh_token_demo_database_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: toor
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
